feat: endpoint to get actions count for 24h #128
GolosChain/cyberway-block-explorer pull request #129
Opened 2020-02-27 12:14 UTC by zxcat

also contains older commit with proposal fixes

2020-02-27 17:19 UTC, bacher requested changes

2020-02-27 17:19 UTC, Bacher commented on server/src/index.js
> +        resolve({ blockTime, actions: totals.actions.count });
Всю эту функцию желательно обернуть в try/catch потому что если например не будет поля count у `resposnse.result.totals.actions` то будет uncaughtException

2020-02-27 17:36 UTC, zxcat commented on server/src/index.js
> +        resolve({ blockTime, actions: totals.actions.count });
поправил: ba65573

2020-02-28 09:10 UTC, bacher approved these changes

2020-02-28 09:12 UTC, merged